# Generated by Django 4.2 on 2023-05-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentProcessing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
