# Generated by Django 4.2 on 2023-05-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentProcessing', '0002_alter_payment_is_paid_alter_payment_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
